// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgBMh1jwKkNvQLEE4tS8dEytvM9yFj-LQ',
    appId: '1:601898303045:web:cdf8c2503fac55d5c9ed2c',
    messagingSenderId: '601898303045',
    projectId: 'bwa-flutix-92a05',
    authDomain: 'bwa-flutix-92a05.firebaseapp.com',
    storageBucket: 'bwa-flutix-92a05.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo0iaoOoY23vP1VobcsBX1FOinxZScpu8',
    appId: '1:601898303045:android:9fe714ab9faf2e47c9ed2c',
    messagingSenderId: '601898303045',
    projectId: 'bwa-flutix-92a05',
    storageBucket: 'bwa-flutix-92a05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF9Gmq9NNvssEA_dYCVIdAsgKpvR-gYvM',
    appId: '1:601898303045:ios:81f4be06d0acc30dc9ed2c',
    messagingSenderId: '601898303045',
    projectId: 'bwa-flutix-92a05',
    storageBucket: 'bwa-flutix-92a05.appspot.com',
    iosClientId: '601898303045-53sp8rmu8as35hm8l8h29vi1ko9941eb.apps.googleusercontent.com',
    iosBundleId: 'com.example.bwaFlutix',
  );
}
